# Generated by Django 3.2.7 on 2021-09-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='menu/food.jpg', upload_to='menu'),
        ),
    ]
